name: PUBLISH

on:
  push:
    branches:
      - develop

jobs:
  open-pr-main:
    name: Open Pull Request to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Open Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: develop
          destination_branch: main
          pr_title: "Merge develop into main (Auto PR via Pipeline)"
          pr_body: |
            PR automatica criada pelo workflow PUBLISH.
            Branch de origem: `develop`
            Destino: `main`

            Iniciado por: ${{ github.actor }}
